#!/usr/bin/bash

# Policy Authentication Agent
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
systemctl --user start hyprpolkitagent
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)

# https://wiki.hyprland.org/FAQ/#some-of-my-apps-take-a-really-long-time-to-open
# https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP --all &

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh

# variables
scripts=~/.scripts

# gsettings
#gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Dark-BL-LB'
#gsettings set org.gnome.desktop.interface font-name 'CaskaydiaCove Nerd Font 9'
#gsettings set org.gnome.desktop.interface icon-theme 'Tokyonight-Moon'
#gsettings set org.gnome.desktop.interface cursor-theme 'Sweet-cursors'

# For nemo
gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty

# notification daemon
swaync &

# waybar
$scripts/launch_waybar &
$scripts/dynamic &

# music daemon
mpd &
g4music &
timedatectl &
# wallpaper
hyprpaper &
sleep 1
~/.scripts/wall &
openrgb -p /home/buddy/.config/OpenRGB/blue.orp
# Applets
$scripts/appindicator.py &
blueman-applet &
nm-applet --indicator &\

# other
#hyprctl setcursor Sweet-cursors 24
wl-paste --watch cliphist store &
notify-send -a aurora "hello $(whoami)" &
#libinput-gestures-setup start &

# sleep 1
mpd-mpris &
hyprctl dispatch movetoworkspacesilent 2,com.github.neithern.g4music
#gpu-screen-recorder -w DP-1 -f 30 -a "default_input|default_output" -q medium -ac opus -c mp4 -o $HOME/Videos/clips -r 300 > ~/Videos/logs.txt

#sleep 1
#sleep 2

/usr/lib/xdg-desktop-portal-hyprland &
/usr/lib/xdg-desktop-portal &
sleep 20
~/.scripts/startclips.sh &
